version: "3.2"

services:
  database:
    container_name: mysql-vegiedo
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pal_dex
      MYSQL_ROOT_PASSWORD: tmdcks2416@
    ports:
      - "6000:3306"
    volumes:
      - "./db/conf.d:/etc/mysql/conf.d"
      - "./db/data:/var/lib/mysql"
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
      - "./data:/data"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    networks:
      - sclee_network

  application:
    container_name: sclee-sev
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2417:2417"
    environment:
      SPRING_DATASOURCE_URL:
        jdbc:mysql://172.17.0.1:6000/pal_dex?useSSL=false
        &useUnicode=true&autoReconnect=true
        &serverTimezone=Asia/Seoul
        &allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "tmdcks2416@"
    depends_on:
      - database
    volumes:
      - ./uploads:/home/sclee-blog-server/uploads
    networks:
      - sclee_network
networks:
  sclee_network:
